backend:
  name: git-gateway
  branch: master

media_folder: src/media
public_folder: static

slug: 
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow
site_url: https://chjweb-static.netlify.com

collections:
  - name: "blog"
    label: "Blogg"
    label_singular: "Inlägg"
    folder: content/blog
    preview_path: "blogg/{{slug}}"
    create: true
    slug: "{{slug}}"     
    editor:
      preview: false
    fields: 
      - { label: "Titel", name: "title", widget: "string", required: true, pattern: ['.{20,60}', "Måste vara mellan 20 och 60 tecken"] }
      - { label: "Publiceringsdatum", name: "date", widget: "datetime", timeFormat: false, dateFormat: "DD MMM, Y", required: true }
      - { label: "Uppdaterades", name: "updated", widget: "datetime", timeFormat: false, dateFormat: "DD MMM, Y" }
      - { label: "Beskrivning", name: "description", widget: "text", pattern: ['.{0,155}', "Max 155 tecken"] , required: true}
      - { label: "Bild", name: "image", widget: "image", required: true }
      - { label: "Innehåll", name: "body", widget: "markdown", required: true }

  - name: "projects"
    label: "Projekt"
    folder: content/projects
    preview_path: "projekt/{{slug}}"
    create: true
    slug: "{{slug}}"
    editor: 
      preview: false
    fields: 
      - { label: "Namn", name: "title", widget: "string", required: true }
      - { label: "Beskrivning", name: "description", widget: "text", required: true, pattern: ['.{300,1000}', "Måste vara mellan 300 och 1000 tecken"] }
      - { label: "Hemsida", name: "website", widget: "string", pattern: ["^https?:\/\/.+..+$", "Måste vara en giltig webbadress som börjar med http/https."] }
      - { label: "Blogginlägg", name: "blogpost", widget: "string", pattern: ["^https?:\/\/(www.)?chjweb.se\/blogg\/.+$", "Måste vara en länk till ett blogginlägg på https://chjweb.se/blogg/"] }
      - { label: "Bild", name: "image", widget: "image" }
