backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /images

slug: 
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "blog"
    label: "Blogg"
    folder: content/blog
    create: true
    slug: "{{slug}}"     
    editor:
      preview: false
    fields: 
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Publiceringsdatum", name: publish-date, widget: "datetime"}
      - { label: "Beskrivning", name: "description", widget: "string" }
      - { label: "innehåll", name: "body", widget: "markdown" }