backend:
  name: git-gateway
  branch: master

media_folder: src/media
public_folder: img

slug: 
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

publish_mode: editorial_workflow
site_url: https://chjweb-static.netlify.com

collections:
  - name: "blog"
    label: "Blogg"
    label_singular: "Inlägg"
    folder: content/blog
    preview_path: "blogg/{{slug}}"
    create: true
    slug: "{{slug}}"     
    editor:
      preview: false
    fields: 
      - { label: "Titel", name: "title", widget: "string", required: true }
      - { label: "Publiceringsdatum", name: publish-date, widget: "datetime", timeFormat: false, dateFormat: "DD MMM, YYY" }
      - { label: "Beskrivning", name: "description", widget: "string" }
      - { label: "Bild", name: "image", widget: "image" }
      - { label: "innehåll", name: "body", widget: "markdown" }